# Generated by Django 5.2.8 on 2025-12-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='print',
            new_name='price',
        ),
    ]
